stages:
  scrape:
    cmd: python src/app.py
    deps:
      - src/app.py
    outs:
      - data/trends.json

  log_mlflow:
    cmd: python src/mlflow_logger.py
    deps:
      - src/mlflow_logger.py
      - data/trends.json
    outs:
      - mlruns/
