name: MLOps CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install "dvc[s3]>=3.50.0"

      - name: Configure DVC remote
        run: |
          dvc remote add -d -f b2remote s3://$B2_BUCKET_NAME
          dvc remote modify b2remote endpointurl $B2_ENDPOINT
          dvc remote modify b2remote access_key_id $B2_KEY_ID
          dvc remote modify b2remote secret_access_key $B2_APP_KEY
        env:
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
          B2_ENDPOINT: ${{ secrets.B2_ENDPOINT }}
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}

      - name: Pull latest dataset
        run: dvc pull -r b2remote || true

      - name: Run scraping stage
        run: dvc repro

      - name: Push updated data to DVC remote
        run: dvc push -r b2remote
